Repository kalviumcommunity/S69_Preetham_Capstone_Ecanent, pull requests merged in 2025-03, with the labels that each got.

#23 relation
  server/Controllers/SubjectController.js
  server/Models/ClassgroupSchema.js
  server/Models/Subjectgroup.js
  server/Models/UserSchema.js
Labels: Review effort 1/5

#24 Update&Delete
  client/src/App.jsx
  client/src/Pages/Profile.css
  client/src/Pages/Profile.jsx
  client/src/assets/arrow_back.png
  client/src/components/Login.css
  client/src/components/Login.jsx
  server/Controllers/AuthController.js
  server/Controllers/UserController.js
  server/Routes/UserRoutes.js
Labels: Review effort 3/5

#26 Arav-to-Preetham
  server/Controllers/UserController.js
Labels: Review effort 2/5

#27 Manoj-To-Preetham
  server/Controllers/ClassController.js
  server/Routes/ClassRoutes.js
Labels: Review effort 2/5
